### ISSUE TITLE
user_place_visit_num.pkl文件无法找到

### ISSUE THREAD

**Issue by Nihilitior** [zhuqunxi/Urban-Region-Function-Classification#1]
请问在运行Feature_extracting/UserID_feature_global中的main文件时
提示需要user_place_visit_num变量
而该变量的生成方式已经被注释掉,且该变量需要读取的./data/tmp/user_place_visit_num.pkl之前也并未生成过
我应该如何得到user_place_visit_num.pkl呢

**Comment by zhuqunxi** [comment]
可以运行下面两句得到user_place_visit_num.pkl

user_place_visit_num = static_user_place_num()
write_pkl(data=user_place_visit_num, fname='./data/tmp/user_place_visit_num.pkl')

**Comment by Nihilitior** [comment]
感谢大佬回复,问题已经得到解决
